import Head from "next/head";
import Link from "next/link";
import Image, { type StaticImageData } from "next/image";
import { useSpringCarousel } from "react-spring-carousel";

import Photo from "@/images/Photo.png";
import AmaIcon from "@/work-icons/ama.png";
import AppleIcon from "@/work-icons/apple.png";
import BncIcon from "@/work-icons/bnc.png";
import GoogleIcon from "@/work-icons/google.png";
import MetlifeIcon from "@/work-icons/metlife.png";
import NikeIcon from "@/work-icons/nike.png";
import PixarIcon from "@/work-icons/pixar.png";
import SamsungIcon from "@/work-icons/samsung.png";
import TxmIcon from "@/work-icons/txm.png";
import UsaaIcon from "@/work-icons/usaa.png";

import Layout from "~/components/layouts/layout";
import { useEffect } from "react";

interface WorksItem {
  image: string | StaticImageData;
  alt: string;
  id: string;
}

const CarouselItem = ({ image, alt }: WorksItem) => (
  <div className="flex h-full w-full flex-col items-center justify-center">
    <Image src={image} alt={alt} width={100} height={40} />
  </div>
);

const Carousel = ({ works }: { works: WorksItem[] }) => {
  const waitTime = 1000 * 5;

  // ESLint is jumping the gun here, let's stop it.
  // eslint-disable-next-line @typescript-eslint/unbound-method
  const { carouselFragment, slideToNextItem } = useSpringCarousel({
    itemsPerSlide: 6,
    gutter: 24,
    withLoop: true,
    items: works.map((item) => ({
      id: item.id,
      renderItem: <CarouselItem {...item} />,
    })),
  });

  useEffect(() => {
    const timer = setInterval(() => {
      slideToNextItem();
    }, waitTime);

    return () => {
      window.clearInterval(timer);
    };
  }, [waitTime, slideToNextItem]);

  return carouselFragment;
};

const staticWorks: WorksItem[] = [
  { image: AmaIcon, alt: "Amazon", id: "amazon" },
  { image: AppleIcon, alt: "Apple", id: "apple" },
  { image: BncIcon, alt: "Barnes and Noble College", id: "barnesAndNoble" },
  { image: GoogleIcon, alt: "Google", id: "google" },
  { image: MetlifeIcon, alt: "MetLife", id: "metlife" },
  { image: NikeIcon, alt: "Nike", id: "nike" },
  { image: PixarIcon, alt: "Pixar", id: "pixar" },
  { image: SamsungIcon, alt: "Samsung", id: "samsung" },
  { image: TxmIcon, alt: "Texas Mutual", id: "texasMutual" },
  { image: UsaaIcon, alt: "USAA", id: "usaa" },
];

export default function Home() {
  const image = Photo;
  const title = "Dante Kelly";
  const body = `I’m a tech professional in Las Vegas working as a full-stack developer and UI/UX designer, building secure and effective applications.

Often I’ll take on additional smaller projects to test out cutting-edge technology in production, and let you know my insights.

If you like one of my experiments, don’t be a stranger, report some issues.`;
  return (
    <>
      <Head>
        <title>Dante Kelly - Portfolio</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout isHome>
        <div className="container flex flex-row items-center justify-center gap-12 px-4 py-16 ">
          <Image src={image} alt="Dante Kelly" width={300} height={305} />
          <div className="flex flex-col gap-5">
            <h1 className="text-5xl font-extrabold text-slate-50">{title}</h1>
            <p className="text-md text-slate-400">{body}</p>
          </div>
        </div>

        <div>
          <p className="text-md mb-[10px] font-medium uppercase text-slate-400">
            Works Used By
          </p>
          <Carousel works={staticWorks} />
        </div>
      </Layout>
    </>
  );
}
