name: pa11y
on: [ push ]
jobs:
  pa11y:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      - run: bun install
      - run: bun run build
      - run: bun start & bunx wait-on http://localhost:3000
      - name: Run pa11y
        run: |
          bun add -g pa11y
          pa11y http://localhost:3000